server:
  port: 40000


spring:
  cloud:
    alicloud:
      access-key: LTAI4GHuuSXMN3zakofPSuyZ
      secret-key: uuBKGDhLJIhKdYyAq2QRxykp5BNNiX
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: gulifry
      sms:
       host: https://zwp.market.alicloudapi.com
       path: /sms/sendv2
       appcode: 3cfe2f50b9a64498bd9117e07cf4b9f6
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: guli-third-party

